spring.application.name=biblioteca

spring.datasource.url=jdbc:postgresql://ep-red-credit-am2l6t35-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_EUXRrLwWu27f

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect